import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { loadGapRegister, summarize } from "../src/core/gap-register.js";
import { loadUpgradeRegister, summarizeUpgrades } from "../src/core/upgrade-register.js";
import { scanDesignCoverage } from "../src/core/design-coverage.js";

const DOC = "docs/42-comprehensive-capability-audit.md";
const START = "<!-- CAPABILITY-AUDIT:START (generated by scripts/render-capability-audit.ts — do not edit by hand) -->";
const END = "<!-- CAPABILITY-AUDIT:END -->";
const ROOT = new URL("../", import.meta.url);

const PHASES = [
  { phase: "M19", title: "Durable Product Surface، API و Event Bus", proposals: "UP-002، UP-007، UP-008، UP-010، UP-005", scope: "وب‌اپ، API contract، event bus، contract testing و tenant-safe command/event boundary" },
  { phase: "M20", title: "Evaluation Integrity و Reproducible Benchmarking", proposals: "UP-011 تا UP-020", scope: "benchmark corpus، replay، contamination، rubric، regression gate و blind evaluation" },
  { phase: "M21", title: "Secure Supply Chain و Runtime Isolation", proposals: "UP-031 تا UP-040", scope: "egress proxy، secret lease، signed manifest، SBOM، dependency policy، injection firewall، microVM و DLP" },
  { phase: "M22", title: "Resilience، SLO، FinOps و Provider Operations", proposals: "UP-042، UP-044، UP-046، UP-049، UP-052 تا UP-060", scope: "crash resume، circuit breaker، error budget، backup drill، pre-run budget، quota، health، cache و energy" },
  { phase: "M23", title: "Delivery Trust و Developer Experience", proposals: "UP-061 تا UP-080", scope: "approval inbox، rollback، worktree، transactional patch، license/secret scan، attestation، CLI/IDE و test matrix" },
  { phase: "M24", title: "Intake، Planning، Capability Graph و Collaboration", proposals: "UP-009، UP-021 تا UP-024، UP-068", scope: "intent، requirement، DAG، capability graph، governed plugin و collaboration boundary" },
  { phase: "M25", title: "Evidence-Grounded Routing و Operations", proposals: "UP-025 تا UP-030، UP-045، UP-047", scope: "source calibration، drift، Pareto، shadow routing، distributed tracing و error taxonomy" },
  { phase: "M26", title: "Secure Knowledge Fabric و Context Packing", proposals: "UP-081 تا UP-086", scope: "code graph، ACL، context budget، tiered memory، stale documentation و lineage" },
  { phase: "M27", title: "Privacy-Aware Retrieval و Local Index", proposals: "UP-087 تا UP-090", scope: "PII، deletion propagation، retrieval evaluation و local-only index" },
  { phase: "M28", title: "Governance، Quality و Transparency", proposals: "UP-091 تا UP-099", scope: "policy، change، model card، fairness، accessibility، marketplace، dashboard و ADR" },
  { phase: "M29", title: "Durable Runtime Foundation", proposals: "GAP-DA-01، GAP-DA-03، GAP-IG-07، GAP-EX-11، GAP-SE-10", scope: "transaction، RLS boundary، outbox، idempotency و durable job envelope" },
  { phase: "M30", title: "Sandbox Execution و Workspace Runtime", proposals: "GAP-EX-01 تا GAP-EX-04، GAP-EX-08، GAP-EX-12", scope: "sandbox، VFS، patch atomic، test adapters، cleanup و escape evidence" },
  { phase: "M31", title: "Connector و Provider Runtime", proposals: "GAP-IG-01، GAP-IG-02، GAP-IG-04، GAP-IG-08، GAP-IN-09", scope: "OAuth، webhook، connector scope، provider adapter، BYOK/free/local و privacy" },
  { phase: "M32", title: "Operations Evidence، SLO، FinOps و Disaster Recovery", proposals: "GAP-OB-01 تا GAP-OB-06", scope: "metrics، trace، SLO، error budget، cost reconciliation، incident و restore drill" },
  { phase: "M33", title: "Product Surface، Approval UX و Client Contracts", proposals: "GAP-UX-01 تا GAP-UX-05، GAP-UX-07، GAP-API-04، GAP-QA-03، GAP-QA-05", scope: "screen states، SSE resume، approval inbox، CLI/IDE، Web App و accessibility" },
  { phase: "M34", title: "Identity، Membership و Access Runtime", proposals: "GAP-CP-01، GAP-CP-02، GAP-CP-04، GAP-CP-05، GAP-CP-08، GAP-CP-10", scope: "session proof، MFA boundary، invitation، role، settings hierarchy و notification" },
  { phase: "M35", title: "Evaluation و Reproducible Benchmark Runtime", proposals: "GAP-IN-01، GAP-IN-02، GAP-IN-10، GAP-IN-13، GAP-QA-01، GAP-QA-02", scope: "dataset provenance، benchmark، scoring، regression gate و human feedback" },
  { phase: "M36", title: "Repository Intelligence و Context Runtime", proposals: "GAP-IN-03، GAP-IN-04، GAP-IN-05، GAP-IN-08، GAP-IN-12، GAP-EX-09", scope: "snapshot، index، ACL context، delegation، path guard و migration boundary" },
  { phase: "M37", title: "Preview، Artifact و Delivery Runtime", proposals: "GAP-EX-05، GAP-EX-07، GAP-EX-10، GAP-PO-01، GAP-PO-03، GAP-QA-04", scope: "preview، signed artifact، retention، deploy adapter، rollback و load boundary" },
  { phase: "M38", title: "Security، Privacy و Governance Runtime", proposals: "GAP-SE-01 تا GAP-SE-09، GAP-DA-06، GAP-OB-06", scope: "STRIDE، isolation، key rotation، deletion، injection، DLP، abuse و egress" },
  { phase: "M39", title: "Agent Interaction و Streaming Runtime", proposals: "GAP-IN-10، GAP-IN-11، GAP-IN-12، GAP-UX-03، GAP-API-04", scope: "structured output، repair، streaming، resume و tool-target guardrail" },
  { phase: "M40", title: "Connector Gateway و Interoperability Runtime", proposals: "GAP-IG-02، GAP-IG-03، GAP-IG-04، GAP-IG-06، GAP-IG-08، GAP-IG-09", scope: "GitHub App، rate/backoff، signed webhook، database introspection و MCP" },
  { phase: "M41", title: "Data Lifecycle، Analytics و Metering Runtime", proposals: "GAP-SE-04، GAP-DA-03 تا GAP-DA-05، GAP-OB-04، GAP-CP-03", scope: "retention، legal hold، event store، analytics، entitlement و search" },
  { phase: "M42", title: "Quality، CI و Verification Runtime", proposals: "GAP-IN-01، GAP-EX-03، GAP-EX-04، GAP-QA-01، GAP-QA-03 تا GAP-QA-05، GAP-PO-02، GAP-PO-05", scope: "toolchain matrix، test adapter، E2E، CI، load/security و accessibility" },
  { phase: "M43", title: "Self-host، Release و Resilience Runtime", proposals: "GAP-EX-10، GAP-OB-05، GAP-OB-06، GAP-PO-01، GAP-PO-03، GAP-PO-04، GAP-PO-06", scope: "self-host packaging، release، backup/recovery، upgrade و chaos" },
  { phase: "M44", title: "Collaboration، Onboarding و Run Workspace", proposals: "GAP-CP-04، GAP-CP-05، GAP-CP-07، GAP-CP-08، GAP-UX-02، GAP-UX-03، GAP-UX-07", scope: "Run collaboration، handoff، onboarding، template، CLI و offline workspace" },
  { phase: "M45", title: "Localization، Design System و Degraded Clients", proposals: "GAP-CP-09، GAP-UX-05، GAP-UX-06، GAP-UX-08", scope: "catalog، fallback، Persian RTL، design token، PWA و offline/degraded client" },
  { phase: "M46", title: "Browser Automation و External Signal Runtime", proposals: "GAP-IG-05، GAP-IN-14", scope: "browser session، allowlist، human handover، provenance و bounded harvesting" },
  { phase: "M47", title: "Legal، Licensing و Enterprise Governance Runtime", proposals: "GAP-SE-08، GAP-LG-01، GAP-LG-04، GAP-LG-05، GAP-PO-04، GAP-PO-06", scope: "Terms/Privacy، output rights، dependency license، disclosure و enterprise upgrade" },
  { phase: "M48", title: "Production Integration Evidence و Controlled Cutover", proposals: "GAP-PO-02، GAP-PO-06، GAP-OB-01، GAP-OB-03، GAP-OB-05، GAP-QA-04", scope: "evidence envelope، readiness، canary، cutover، rollback و cross-phase integration" },
  { phase: "M49", title: "Platform Connections، OAuth/PKCE و Consent", proposals: "GAP-IG-02، GAP-IG-04، GAP-IG-08، GAP-CP-08", scope: "platform registry، OAuth/PKCE، scope، consent، credential reference و revoke" },
  { phase: "M50", title: "Unified Connector Capabilities و Cross-platform Actions", proposals: "GAP-IG-02، GAP-IG-06، GAP-IG-08، GAP-IG-09، GAP-IN-12", scope: "capability manifest، normalized operation، scope negotiation، adapter و action approval" },
  { phase: "M51", title: "Cross-platform Context Handoff و Deep Links", proposals: "GAP-UX-02، GAP-UX-03، GAP-IG-09، GAP-CP-08", scope: "signed deep link، context handoff، import/export و one-time capability" },
  { phase: "M52", title: "Platform Sync، Webhook و Conflict Resolution", proposals: "GAP-IG-04، GAP-IG-08، GAP-IG-09، GAP-OB-01", scope: "signed webhook، cursor، dedupe، outbox، retry و conflict review" },
  { phase: "M53", title: "Connection Center، Health، Recovery و Fallback", proposals: "GAP-UX-02، GAP-UX-05، GAP-IG-08، GAP-PO-01، GAP-SE-08", scope: "connection center، health، reconnect، revoke، local/BYOK/free/read-only fallback" },
  { phase: "M54", title: "Visual App Studio و Prompt-to-UI Design", proposals: "GAP-UX-02، GAP-UX-03، GAP-UX-05، GAP-QA-05، GAP-UX-06", scope: "prompt-to-canvas، UX flow، visual prototype، design token و interactive preview" },
  { phase: "M55", title: "Design-to-code، Component Handoff و UX Verification", proposals: "GAP-UX-02، GAP-UX-05، GAP-QA-05، GAP-EX-02، GAP-EX-04", scope: "component mapping، sandboxed code handoff، allowed paths، accessibility و RTL review" },
  { phase: "M56", title: "Web AI Model Discovery و Free API Verification", proposals: "GAP-IN-14، GAP-IN-17، GAP-IG-08", scope: "bounded web discovery، model card، provenance، short description و free API evidence" },
  { phase: "M57", title: "Comprehensive AI Directory و Model Cards", proposals: "GAP-IN-17، GAP-IN-18، GAP-DA-05، GAP-UX-02", scope: "taxonomy، category، search، model card، health/freshness و free API badge" },
  { phase: "M58", title: "Model Catalog Governance و Safe Activation", proposals: "GAP-IN-17، GAP-IN-18، GAP-IG-08، GAP-PO-01", scope: "candidate-to-listed lifecycle، publication review، activation، health و local/BYOK/free fallback" },
  { phase: "M59", title: "Visual Studio Integration و Reviewable Preview", proposals: "GAP-UX-02، GAP-UX-03، GAP-UX-05، GAP-QA-05، GAP-UX-06، GAP-UX-08", scope: "preview surface، artifact، screenshot، collaboration event و publish boundary" },
  { phase: "M60", title: "Model Evaluation، Trust و Activation Gate", proposals: "GAP-IN-01، GAP-IN-10، GAP-IN-13، GAP-QA-01، GAP-QA-02", scope: "reproducible benchmark، safety/quality، trust profile و model activation gate" },
  { phase: "M61", title: "Model Provider Runtime و Intelligent Routing", proposals: "GAP-IG-02، GAP-IG-08، GAP-IN-10، GAP-OB-04، GAP-PO-01", scope: "provider endpoint، privacy route، quota، local/free/paid fallback و adapter boundary" },
  { phase: "M62", title: "AI Workflow Builder و Agent Graphs", proposals: "GAP-IN-08، GAP-IN-12، GAP-UX-07، GAP-CP-04، GAP-CP-05", scope: "model/tool graph، schema، approval، sandbox و workflow handoff" },
  { phase: "M63", title: "AI Platform Operations، Quota و Governance", proposals: "GAP-OB-01، GAP-OB-03، GAP-OB-04، GAP-OB-05، GAP-SE-08، GAP-PO-02، GAP-PO-06", scope: "health، quota/cost، incident response، dashboard و operational evidence" },
  { phase: "M64", title: "Product Control-plane UI، API و Approval Surfaces", proposals: "GAP-API-05، GAP-UX-02، GAP-UX-03، GAP-UX-05، GAP-QA-03", scope: "tenant-safe API، screen states، approval inbox، error/degraded UX و session boundary" },
  { phase: "M65", title: "Durable Persistence، RLS، Outbox و Job Leases", proposals: "GAP-DA-03، GAP-DA-04، GAP-DA-05، GAP-OB-01، GAP-EX-09", scope: "transaction، RLS، optimistic version، event bus، outbox و durable worker lease" },
  { phase: "M66", title: "Sandbox Execution و Workspace Integration", proposals: "GAP-EX-01، GAP-EX-02، GAP-EX-03، GAP-EX-04، GAP-EX-12، GAP-IN-12، GAP-SE-05، GAP-SE-06", scope: "untrusted sandbox، atomic patch، test adapter، limits، cleanup و execution evidence" },
  { phase: "M67", title: "External Integration Gates و Adapter Probes", proposals: "GAP-IG-02، GAP-IG-03، GAP-IG-04، GAP-IG-06، GAP-IG-08، GAP-IG-09، GAP-IN-10، GAP-IN-11", scope: "connector/provider/webhook/database/MCP manifest، probe، tenant isolation و rollback" },
  { phase: "M68", title: "Pilot Release، E2E و Release Gates", proposals: "GAP-QA-03، GAP-QA-04، GAP-QA-05، GAP-PO-02، GAP-PO-03، GAP-PO-05، GAP-PO-06، GAP-OB-03، GAP-OB-06", scope: "pilot cohort، E2E، accessibility/security، canary، rollback و release readiness" },
  { phase: "M69", title: "Enterprise Identity، Membership و Delegation", proposals: "GAP-CP-02، GAP-CP-04، GAP-CP-05، GAP-CP-08", scope: "OIDC/SAML، MFA، invitation، role transition، deprovision و delegation" },
  { phase: "M70", title: "Privacy Lifecycle، Data Rights و Deletion Evidence", proposals: "GAP-SE-04، GAP-SE-06، GAP-LG-01، GAP-LG-04، GAP-DA-04", scope: "retention، DSAR، legal hold، deletion propagation، tombstone و residual proof" },
  { phase: "M71", title: "Developer Experience، API Contract و SDK/CLI", proposals: "GAP-API-05، GAP-UX-07، GAP-IG-09، GAP-PO-06", scope: "API versioning، schema compatibility، SDK، Forge CLI و signed webhook client" },
  { phase: "M72", title: "Extension Marketplace و Plugin Trust", proposals: "GAP-IG-03، GAP-IG-06، GAP-SE-05، GAP-SE-06، GAP-PO-04", scope: "manifest، permission، signature، sandbox، scan، review و installation lifecycle" },
  { phase: "M73", title: "Platform Resilience، SLO، Backup/Restore و Chaos", proposals: "GAP-OB-01، GAP-OB-03، GAP-OB-05، GAP-OB-06، GAP-PO-01، GAP-PO-03", scope: "SLO، error budget، backup/restore، incident، failover و bounded chaos" },
  { phase: "M74", title: "Product Experience، Client Contracts و Accessibility", proposals: "GAP-UX-02، GAP-UX-03، GAP-UX-05، GAP-UX-07، GAP-API-05، GAP-QA-03، GAP-QA-05", scope: "screen states، tenant-safe client action، idempotency، RTL و accessibility evidence" },
  { phase: "M75", title: "Evaluation Harness، Benchmark و Regression Gates", proposals: "GAP-IN-01، GAP-IN-10، GAP-IN-13، GAP-QA-01، GAP-QA-02", scope: "scenario provenance، seed، blind scoring، safety/contamination، score و regression gate" },
  { phase: "M76", title: "Execution Fabric، Workspace/VFS و Sandbox", proposals: "GAP-EX-01، GAP-EX-02، GAP-EX-03، GAP-EX-04، GAP-EX-12، GAP-IN-04، GAP-IN-12", scope: "runtime matrix، allowed path، network/limits، atomic patch، test adapter و cleanup" },
  { phase: "M77", title: "Connector Delivery، Webhook و Rate Limits", proposals: "GAP-IG-02، GAP-IG-03، GAP-IG-04، GAP-IG-06، GAP-IG-08، GAP-IG-09", scope: "connector manifest، scope/token، signed ingress، dedupe، Retry-After و normalized action" },
  { phase: "M78", title: "Self-host Release، CI Evidence و Upgrade Gates", proposals: "GAP-PO-01، GAP-PO-02، GAP-PO-03، GAP-PO-05، GAP-PO-06، GAP-EX-10، GAP-OB-05، GAP-QA-04", scope: "artifact/SBOM/signature، CI، Compose/Kubernetes، canary، backup، migration و rollback" },
  { phase: "M79", title: "Secure Knowledge Fabric، Context و Repository Intelligence", proposals: "GAP-IN-03، GAP-IN-04، GAP-IN-05، GAP-IN-08، GAP-IN-12، GAP-EX-09", scope: "repository index، context assembly، semantic memory، ACL، lineage و bounded delegation" },
  { phase: "M80", title: "Prompt Safety، Injection Detection و Output Trust", proposals: "GAP-SE-05، GAP-SE-06، GAP-IN-10، GAP-IN-11، GAP-QA-02", scope: "injection، canary، secret/tenant scan، structured output و bounded repair/fallback" },
  { phase: "M81", title: "Collaboration، Onboarding و Usage Control", proposals: "GAP-CP-03، GAP-CP-04، GAP-CP-05، GAP-CP-07، GAP-CP-08، GAP-UX-07، GAP-DA-03، GAP-OB-04", scope: "Run collaboration، first-run، local/BYOK/free، notification، metering و entitlement" },
  { phase: "M82", title: "Integration Adapters و Browser Runtime", proposals: "GAP-IG-02، GAP-IG-03، GAP-IG-05، GAP-IG-06، GAP-IG-08، GAP-IG-09", scope: "GitHub App، MCP، database، browser session، scope، probe و rollback evidence" },
  { phase: "M83", title: "Data Governance، Analytics، Legal و Disclosure", proposals: "GAP-DA-03، GAP-DA-04، GAP-DA-05، GAP-LG-01، GAP-LG-04، GAP-LG-05، GAP-SE-08", scope: "event envelope، governed analytics، legal acceptance، output rights و vulnerability disclosure" },
  { phase: "M84", title: "Agent Orchestration، Workflow Graph و Checkpoints", proposals: "GAP-IN-08، GAP-IN-12، GAP-EX-09، GAP-OB-01، GAP-CP-05", scope: "workflow DAG، scheduling، checkpoint، resume و tool-call approval" },
  { phase: "M85", title: "Public API، Worker Lease و Stream Runtime", proposals: "GAP-API-05، GAP-OB-01، GAP-EX-09، GAP-IN-11، GAP-DA-03", scope: "tenant-safe API، worker lease/fencing، stream resume و completion evidence" },
  { phase: "M86", title: "Provider Economics، Quota و Routing", proposals: "GAP-OB-04، GAP-CP-03، GAP-IN-10، GAP-PO-01، GAP-IG-08", scope: "provider offer، local/BYOK/free/paid route، quota، RPM، budget و reconciliation" },
  { phase: "M87", title: "Quality Integration، E2E، Load/Security و Accessibility", proposals: "GAP-QA-03، GAP-QA-04، GAP-QA-05، GAP-PO-02، GAP-PO-05", scope: "reproducible scenario، E2E، tenant probe، load/security threshold و accessibility evidence" },
  { phase: "M88", title: "Release Certification، Canary و Controlled Cutover", proposals: "GAP-PO-01، GAP-PO-02، GAP-PO-03، GAP-PO-05، GAP-PO-06، GAP-EX-10، GAP-OB-05", scope: "release candidate، artifact/SBOM/signature، canary، promotion، incident hold و rollback" },
  { phase: "M89", title: "Observability، SLO Measurement و Incident Command", proposals: "GAP-OB-01، GAP-OB-03، GAP-OB-04، GAP-OB-06", scope: "telemetry، SLO، alert evaluation و incident runbook action" },
  { phase: "M90", title: "Durable Data Plane، Event Store و Governed Search", proposals: "GAP-DA-01، GAP-DA-03، GAP-DA-04، GAP-DA-05، GAP-EX-09", scope: "versioned entity، append-only event، migration safety و ACL/tenant search" },
  { phase: "M91", title: "Billing، Entitlements و Usage Reconciliation", proposals: "GAP-CP-03، GAP-OB-04، GAP-PO-04، GAP-IG-08", scope: "plan، allowance، usage charge، invoice delta و subscription transition" },
  { phase: "M92", title: "Human Approval، Review Queue و Escalation", proposals: "GAP-CP-04، GAP-CP-05، GAP-CP-08، GAP-PO-06، GAP-SE-08", scope: "approval request، assignment، decision، separation of duties و escalation" },
  { phase: "M93", title: "Deployment Operations، Environment Promotion و Self-host", proposals: "GAP-PO-01، GAP-PO-03، GAP-PO-04، GAP-EX-10، GAP-OB-05، GAP-SE-08", scope: "adapter، promotion، smoke/migration evidence، backup و no-clobber self-host config" },
  { phase: "M94", title: "Retrieval، Semantic Memory و Human Feedback", proposals: "GAP-IN-03، GAP-IN-05، GAP-IN-13، GAP-SE-04", scope: "semantic memory، governed retrieval، quality evidence و feedback/invalidation" },
  { phase: "M95", title: "Supply-chain، Artifact Provenance و Injection Security", proposals: "GAP-SE-01، GAP-SE-05، GAP-SE-06، GAP-EX-12، GAP-PO-04", scope: "dependency، SBOM/provenance/signature، secret lease و injection guard" },
  { phase: "M96", title: "Browser Automation، External Signals و Webhook Delivery", proposals: "GAP-IG-04، GAP-IG-05، GAP-IN-14، GAP-IG-09", scope: "browser session، bounded harvesting، source trust، signed webhook و replay guard" },
  { phase: "M97", title: "Localization، RTL Accessibility و Degraded Clients", proposals: "GAP-CP-09، GAP-UX-05، GAP-UX-06، GAP-UX-08", scope: "locale catalog، Persian RTL، accessibility و offline/read-only/local-only policy" },
  { phase: "M98", title: "Project Templates، Workspace Bootstrap و Handoff", proposals: "GAP-CP-05، GAP-CP-07، GAP-CP-08، GAP-DA-03، GAP-UX-07", scope: "template، no-clobber bootstrap، context/diff/test handoff و collaboration comments" },
  { phase: "M99", title: "Agent Delegation، Structured Streaming و Tool Safety", proposals: "GAP-IN-08، GAP-IN-10، GAP-IN-11، GAP-IN-12، GAP-API-04", scope: "delegation contract، bounded repair، stream resume و tool-target guard" },
  { phase: "M100", title: "Durable Workflow، Queue و Scheduling", proposals: "GAP-EX-11، GAP-EX-13، GAP-IG-07، GAP-DA-04، GAP-OB-01", scope: "trigger، job lease، retry، DLQ، idempotency و worker boundary" },
  { phase: "M101", title: "Connector Platform، OAuth/PKCE و GitHub App Gates", proposals: "GAP-IG-01، GAP-IG-02، GAP-IG-03، GAP-IG-06، GAP-IG-08", scope: "OAuth، consent، scope، GitHub App، read-only adapter و rate-limit" },
  { phase: "M102", title: "Privacy Lifecycle، Retention و Tenant Boundary", proposals: "GAP-SE-02، GAP-SE-03، GAP-SE-04، GAP-SE-06، GAP-SE-10", scope: "retention، erasure، legal hold، RLS probe و output privacy filter" },
  { phase: "M103", title: "Evaluation Harness، E2E و Release Quality", proposals: "GAP-IN-01، GAP-IN-02، GAP-IN-15، GAP-QA-01، GAP-QA-03، GAP-QA-04، GAP-QA-05", scope: "dataset provenance، replay، regression، E2E، load/security/accessibility و rollback" },
  { phase: "M104", title: "API Contracts، Versioning و Stream Reconnect", proposals: "GAP-API-01، GAP-API-03، GAP-API-04، GAP-API-05، GAP-API-06، GAP-API-07", scope: "versioned API، error taxonomy، SSE cursor/replay و rate-limit evidence" },
  { phase: "M105", title: "Identity، Membership و MFA Boundary", proposals: "GAP-CP-01، GAP-CP-02، GAP-CP-04، GAP-CP-10، GAP-SE-03", scope: "session، invitation، role transition، MFA و deprovision" },
  { phase: "M106", title: "Artifact Lifecycle، Preview و Signed Delivery", proposals: "GAP-EX-05، GAP-EX-07، GAP-PO-01، GAP-PO-03، GAP-PO-04", scope: "artifact provenance، preview isolation، signed URL، retention و rollback" },
  { phase: "M107", title: "Observability، SLO، Incident Command و FinOps", proposals: "GAP-OB-01، GAP-OB-02، GAP-OB-03، GAP-OB-04، GAP-OB-06", scope: "telemetry، SLO/error budget، incident runbook و cost reconciliation" },
  { phase: "M108", title: "Self-host، Backup/Restore و Controlled Cutover", proposals: "GAP-PO-01، GAP-PO-02، GAP-PO-03، GAP-PO-05، GAP-PO-06، GAP-OB-05، GAP-OB-06", scope: "package، encrypted restore، canary، rollback و bounded chaos" },
  { phase: "M109", title: "Context Assembly و Repository Intelligence", proposals: "GAP-IN-03، GAP-IN-04، GAP-IN-05، GAP-IN-08، GAP-IN-12", scope: "repository snapshot/index، context budget، citation و stale-source quality" },
  { phase: "M110", title: "Model Discovery، AI Directory و Free API Verification", proposals: "GAP-IN-14، GAP-IN-17، GAP-IN-18، GAP-IG-08، GAP-LG-02", scope: "candidate، model card، endpoint probe، quota/ToS و activation fallback" },
  { phase: "M111", title: "Plugin Marketplace و Extension Trust", proposals: "GAP-IG-03، GAP-IG-06، GAP-SE-05، GAP-SE-06، GAP-PO-04", scope: "manifest، permission، attestation، sandbox install و invocation" },
  { phase: "M112", title: "Product Collaboration، Onboarding و Notifications", proposals: "GAP-CP-04، GAP-CP-05، GAP-CP-08، GAP-UX-01، GAP-UX-02، GAP-UX-04", scope: "onboarding، notification، approval surface و collaborative Run" },
  { phase: "M113", title: "Data Plane، Event Store، Search و Analytics", proposals: "GAP-DA-01، GAP-DA-03، GAP-DA-04، GAP-DA-05، GAP-OB-04", scope: "seed fixture، append-only event، governed search و analytics evidence" },
  { phase: "M114", title: "Legal، Licensing، Disclosure و Output Rights", proposals: "GAP-LG-01، GAP-LG-02، GAP-LG-04، GAP-LG-05، GAP-SE-08", scope: "policy، output rights، provider terms و vulnerability disclosure" },
  { phase: "M115", title: "Provider Routing، Quota و Economics", proposals: "GAP-IN-06، GAP-IN-07، GAP-IN-09، GAP-OB-04، GAP-IG-08", scope: "offer، privacy-aware route، quota/cooldown، fallback و cost evidence" },
  { phase: "M116", title: "Platform Sync، Conflict Resolution و Connection Health", proposals: "GAP-IG-04، GAP-IG-07، GAP-IG-08، GAP-IG-09، GAP-PO-01", scope: "sync connection، cursor/dedupe، conflict review و fallback health" },
  { phase: "M117", title: "Abuse Prevention، DLP و Safety Governance", proposals: "GAP-SE-05، GAP-SE-06، GAP-SE-09، GAP-IG-05، GAP-QA-04", scope: "abuse score/action، DLP، malware/spam guard و prohibited activity boundary" },
  { phase: "M118", title: "Production Evidence، Readiness و Cross-phase Cutover", proposals: "GAP-PO-02، GAP-PO-06، GAP-OB-05، GAP-OB-06، GAP-QA-03، GAP-QA-04", scope: "evidence layer، readiness، canary، rollback و cutover gate" },
  { phase: "M119", title: "Durable Tenant Transactions، RLS، Migration Safety و Transactional Outbox", proposals: "GAP-DA-07", scope: "tenant transaction، RLS denial، migration، outbox و no-clobber" },
  { phase: "M120", title: "Verification Matrix، CI، Security، Accessibility و Load Evidence", proposals: "GAP-QA-07", scope: "reproducibility، pipeline artifacts، security، accessibility و bounded load" },
  { phase: "M121", title: "SDK/API Compatibility، Safe CLI، Config Bootstrap و Developer Handoff", proposals: "GAP-API-08", scope: "compatibility، path/command safety، config و handoff" },
  { phase: "M122", title: "Key Rotation، Privacy Erasure، Deletion Proof و Backup Retention", proposals: "GAP-SE-12", scope: "key lifecycle، erasure propagation، immutable proof و retention" },
  { phase: "M123", title: "Capacity Planning، Circuit Breaker، Failure Injection و Resilience Operations", proposals: "GAP-PO-07", scope: "capacity، breaker، bounded failure experiment و alert" },
  { phase: "M124", title: "Audit Evidence Ledger، Provenance و Replay", proposals: "GAP-AUD-01", scope: "immutable audit، evidence provenance، tenant replay و retention" },
  { phase: "M125", title: "Identity Continuity، Session Revocation، Delegation و MFA Recovery", proposals: "GAP-CP-14", scope: "session lifecycle، membership delegation، role safety و recovery" },
  { phase: "M126", title: "Connector Consent، Signed Webhook Delivery و Reconciliation", proposals: "GAP-IG-12", scope: "consent، webhook، dedupe/cursor، conflict و action safety" },
  { phase: "M127", title: "Benchmark Corpus، Deterministic Replay و Release Quality", proposals: "GAP-QA-08", scope: "corpus، replay، regression، E2E و rollback evidence" },
  { phase: "M128", title: "FinOps، Usage Ledger، Quota Scheduling و Provider Allocation", proposals: "GAP-OB-07", scope: "append-only usage، quota، provider allocation و cost reconciliation" },
  { phase: "M129", title: "API Evolution، Schema Migration و Stream Reconnect", proposals: "GAP-API-09", scope: "versioning، errors، stream cursor و migration compatibility" },
  { phase: "M130", title: "Artifact Supply Chain، SBOM و Attestation", proposals: "GAP-SE-13", scope: "artifact admission، dependency trust، secret lease و egress" },
  { phase: "M131", title: "Approval Operations، Human Review و Escalation", proposals: "GAP-CP-15", scope: "approval queue، reviewer، signed decision و escalation" },
  { phase: "M132", title: "Knowledge ACL، Freshness و Context Lineage", proposals: "GAP-IN-19", scope: "trusted source، ACL context، freshness، lineage و index" },
  { phase: "M133", title: "Self-host Upgrade، Backup Restore و Controlled Cutover", proposals: "GAP-PO-08", scope: "release package، restore، canary، rollback و resilience drill" },
  { phase: "M134", title: "Data Portability و Controlled Import", proposals: "GAP-DA-08", scope: "portable manifest، redaction، dry-run، conflict و rollback" },
  { phase: "M135", title: "Device Pairing و Local Trust", proposals: "GAP-CP-16", scope: "device identity، pairing challenge، scoped grant و revocation" },
  { phase: "M136", title: "Policy Distribution و Configuration Drift", proposals: "GAP-SE-14", scope: "signed bundle، enforcement، drift و exception" },
  { phase: "M137", title: "Incident Case، Containment و Postmortem", proposals: "GAP-PO-09", scope: "signal، case، bounded containment و learning loop" },
  { phase: "M138", title: "Privacy-preserving Telemetry و Feedback", proposals: "GAP-OB-08", scope: "consent، sampling، redaction، feedback و retention" },
  { phase: "M139", title: "Observability SLO و Trace Integrity", proposals: "GAP-OB-09", scope: "SLO، error budget، distributed trace و alert routing" },
  { phase: "M140", title: "Full-text Search و Query Governance", proposals: "GAP-DA-09", scope: "ACL index، bounded query، result integrity و export audit" },
  { phase: "M141", title: "Workflow Scheduler و Trigger Runtime", proposals: "GAP-EX-14", scope: "schedule، trigger، dedupe، lease و concurrency" },
  { phase: "M142", title: "Artifact Lifecycle و Preview Isolation", proposals: "GAP-EX-15", scope: "artifact retention، safe preview، signed delivery و cleanup" },
  { phase: "M143", title: "Operator Console و Live Run UX", proposals: "GAP-UX-10", scope: "redacted view، live event، safe action و accessibility evidence" },
  { phase: "M144", title: "Public API Surface و OpenAPI Compatibility", proposals: "GAP-API-10", scope: "OpenAPI document، endpoint contract، compatibility و request admission" },
  { phase: "M145", title: "Connector SDK و OAuth/PKCE Lifecycle", proposals: "GAP-IG-13", scope: "manifest، OAuth، token lease و signed webhook" },
  { phase: "M146", title: "Workspace VFS و Sandbox Resource Boundary", proposals: "GAP-EX-16", scope: "snapshot، path guard، budget، diff و rollback" },
  { phase: "M147", title: "Tenant Isolation و RLS Proof", proposals: "GAP-SE-15", scope: "RLS policy، cross-tenant probe، access و proof bundle" },
  { phase: "M148", title: "E2E Release Acceptance و Readiness", proposals: "GAP-QA-09", scope: "acceptance plan، deterministic gates، go/no-go و readiness review" },
  { phase: "M149", title: "Durable Worker Queue، Retry و DLQ", proposals: "GAP-EX-17", scope: "job envelope، queue policy، lease، retry و DLQ replay" },
  { phase: "M150", title: "Database Migration و Schema Governance", proposals: "GAP-DA-10", scope: "expand/contract، schema change، migration run، RLS و rollback" },
  { phase: "M151", title: "GitHub App و Webhook/Action Integration", proposals: "GAP-IG-14", scope: "installation، token lease، webhook و repository action" },
  { phase: "M152", title: "Preview Environment و Deployment Routing", proposals: "GAP-EX-18", scope: "environment، port lease، route، TLS و deployment target" },
  { phase: "M153", title: "Product E2E Orchestration و Failure Containment", proposals: "GAP-QA-10", scope: "flow plan، step evidence، cleanup، failure و bounded retry" },
  { phase: "M159", title: "Data Residency و Regional Routing", proposals: "GAP-SE-17", scope: "classification، placement، cross-border transfer و replica deletion proof" },
  { phase: "M160", title: "Feature Flags و Progressive Rollout", proposals: "GAP-CP-18", scope: "flag lifecycle، cohort، canary، SLO guardrail و kill switch" },
  { phase: "M161", title: "Workload Identity و Service-account Leases", proposals: "GAP-IG-16", scope: "issuer proof، least privilege، short lease، rotation و revoke" },
  { phase: "M162", title: "Data Rights، Export و Deletion Orchestration", proposals: "GAP-DA-11", scope: "identity proof، encrypted export، legal hold و residual deletion proof" },
  { phase: "M163", title: "FinOps Budget Guardrails و Usage Reconciliation", proposals: "GAP-OB-10", scope: "budget، reservation، provider receipt، hard stop و circuit guardrail" },
  { phase: "M164", title: "Structured Output Repair و Response Safety", proposals: "GAP-IN-20", scope: "output contract، bounded repair، refusal، redaction و safety scan" },
  { phase: "M165", title: "Agent Delegation و Capability Tokens", proposals: "GAP-IG-17", scope: "delegation، capability token، no escalation، result و revoke" },
  { phase: "M166", title: "Cancellation و Compensation Runtime", proposals: "GAP-EX-19", scope: "cancel request، checkpoint، lease revoke، compensation و cleanup" },
  { phase: "M167", title: "Reproducible Build و Release Manifest", proposals: "GAP-PO-11", scope: "hermetic build، SBOM، provenance، scan، rollback و promotion" },
  { phase: "M168", title: "Outbound Webhook و Callback Delivery", proposals: "GAP-IG-18", scope: "endpoint، signature، delivery retry، DLQ و bounded replay" },
  { phase: "M169", title: "Context Provenance و Prompt-injection Firewall", proposals: "GAP-IN-21", scope: "context envelope، source trust، freshness، citation و injection scan" },
  { phase: "M170", title: "Tool Action Boundary و Transactional Approval", proposals: "GAP-EX-20", scope: "action plan، precondition، approval، protected target و commit evidence" },
  { phase: "M171", title: "Offline Sync و Conflict Resolution", proposals: "GAP-UX-11", scope: "snapshot، cursor sync، conflict، no-clobber و degraded client" },
  { phase: "M172", title: "Accessibility و Localization Verification", proposals: "GAP-QA-11", scope: "locale catalog، RTL، WCAG AA، browser evidence و CI gate" },
  { phase: "M173", title: "Incident Learning و Runbook Automation", proposals: "GAP-PO-12", scope: "signal، case، containment، runbook و corrective learning" },
  { phase: "M174", title: "Prompt Experimentation و Rollback", proposals: "GAP-IN-22", scope: "variant registry، deterministic assignment، metric evidence، holdout و rollback" },
  { phase: "M175", title: "Multi-model Consensus و Voting", proposals: "GAP-IN-23", scope: "panel، independent vote، quorum، threshold، evidence و tie-break" },
  { phase: "M176", title: "Agent-to-agent Protocol و Interoperability", proposals: "GAP-IG-19", scope: "manifest، capability، signed message، typed response و bounded handoff" },
  { phase: "M177", title: "Prompt Cache Integrity و Privacy", proposals: "GAP-SE-18", scope: "tenant namespace، encryption، poisoning scan، expiry و replica purge" },
  { phase: "M178", title: "Deployment Adapter و Release Target Boundary", proposals: "GAP-PO-13", scope: "target registry، preflight، adapter، smoke evidence و rollback" },
  { phase: "M179", title: "Pull-request Quality و Commit Provenance", proposals: "GAP-PO-14", scope: "commit provenance، PR quality، checks، merge guard و changelog" },
  { phase: "M180", title: "Agent Graph Orchestration و Durable Checkpoints", proposals: "GAP-EX-21", scope: "acyclic graph، bounded task، lease، checkpoint و transition" },
  { phase: "M181", title: "Performance Budget و Load Shedding", proposals: "GAP-OB-11", scope: "performance budget، admission، load evidence، degrade و shed" },
  { phase: "M182", title: "Onboarding و Safe First Run", proposals: "GAP-CP-19", scope: "consent، mode، synthetic fixture، sandbox و first-run evidence" },
  { phase: "M183", title: "Service Entitlement، SLA و Degraded Disclosure", proposals: "GAP-CP-20", scope: "capability، quota، SLA evidence، fallback و honest disclosure" },
  { phase: "M184", title: "Graph Engine Compatibility و State Interop", proposals: "GAP-EX-22", scope: "adapter manifest، state handoff، node binding، checkpoint و replay compatibility" },
  { phase: "M185", title: "Repository Intelligence و Retrieval Evidence", proposals: "GAP-IN-24", scope: "snapshot، exact-commit retrieval، ACL، code evidence و deletion refresh" },
  { phase: "M186", title: "Human Feedback و Preference Governance", proposals: "GAP-QA-12", scope: "consent، rubric، privacy/bias review، bounded update و disclosure" },
  { phase: "M187", title: "Dependency Risk و Vulnerability Response", proposals: "GAP-SE-19", scope: "digest/lock، license، advisory، patch، quarantine و rollback" },
  { phase: "M188", title: "Schema Evolution و Consumer Compatibility", proposals: "GAP-API-11", scope: "versioned schema، expand-contract، consumer proof، cutover و rollback" },
  { phase: "M189", title: "Release Provenance و Promotion Evidence", proposals: "GAP-PO-15", scope: "artifact/source/build hash، SBOM، attestation، canary و rollback" },
  { phase: "M190", title: "Egress Policy و Destination Governance", proposals: "GAP-SE-20", scope: "destination، data class، DNS/TLS، DLP، consent و credential lease" },
  { phase: "M191", title: "Retention، Legal Hold و Secure Erasure", proposals: "GAP-DA-12", scope: "retention، replica/backup purge، legal hold، idempotency و residual proof" },
  { phase: "M192", title: "Recovery، Chaos و Failover Evidence", proposals: "GAP-OB-12", scope: "bounded drill، RTO/RPO، checkpoint، fencing، quorum و restore proof" },
  { phase: "M193", title: "Tenant Fairness و Queue Scheduling", proposals: "GAP-EX-23", scope: "quota، max share، starvation، allocation lease و fairness evidence" },
  { phase: "M194", title: "Runtime Evidence Envelope و Claim Verification", proposals: "GAP-OB-13", scope: "evidence envelope، claim verification، contradiction، replay و disclosure" },
  { phase: "M195", title: "Provider Health و Circuit Recovery", proposals: "GAP-IG-20", scope: "health sample، quota، circuit، cooldown، probe و fallback route" },
  { phase: "M196", title: "Plugin Capability Sandbox و Extension Certification", proposals: "GAP-SE-21", scope: "manifest، permission، sandbox، scan، certification و revocation" },
  { phase: "M197", title: "Notification Delivery و Preference Governance", proposals: "GAP-CP-21", scope: "intent، consent، preference، dedupe، delivery و escalation" },
  { phase: "M198", title: "Model Catalog Freshness و Capability Disclosure", proposals: "GAP-IN-25", scope: "model card، provenance، freshness، activation، fallback و retirement" },
  { phase: "M199", title: "Intent Normalization و Scope Freeze", proposals: "GAP-CP-22", scope: "intent، constraints، scope decision، plan contract و immutable freeze" },
  { phase: "M200", title: "Side-effect Journal و Idempotent Commit", proposals: "GAP-EX-24", scope: "journal، idempotency، precondition، atomic commit، receipt و compensation" },
  { phase: "M201", title: "Connector Reconciliation و Drift Repair", proposals: "GAP-IG-21", scope: "snapshot، cursor، revisions، conflict، no-clobber و drift evidence" },
  { phase: "M202", title: "Approval Integrity و Decision Expiry", proposals: "GAP-CP-23", scope: "signed decision، policy match، expiry، revocation و second reviewer" },
  { phase: "M203", title: "Privacy-preserving Analytics و Aggregation", proposals: "GAP-OB-14", scope: "consent، sampling، privacy budget، noise، k-anonymity و deletion propagation" },
  { phase: "M204", title: "Run Handoff و Human Takeover", proposals: "GAP-CP-24", scope: "pause/resume، checkpoint، lease، human takeover، replay safety و cleanup" },
  { phase: "M205", title: "Capability Attestation و Trust-bound Activation", proposals: "GAP-SE-22", scope: "attestation، artifact/environment match، scope، revocation و activation gate" },
  { phase: "M206", title: "Region-bound Processing و Residency Enforcement", proposals: "GAP-DA-13", scope: "region routing، provider location، transfer approval، encryption و deletion" },
  { phase: "M207", title: "Action Simulation و Blast-radius Preview", proposals: "GAP-EX-25", scope: "dry-run، snapshot/diff، affected resources، precondition و rollback" },
  { phase: "M208", title: "Policy Change Control و Rollback", proposals: "GAP-SE-23", scope: "policy diff، separation of duties، canary، signed promotion و rollback evidence" },
] as const;

function evidenceBase(): Map<string, string> {
  const excluded = new Set(["16-gap-analysis.md", "17-design-coverage.md", "23-upgrade-contracts.md", "42-comprehensive-capability-audit.md"]);
  const files = new Map<string, string>();
  for (const name of readdirSync(new URL("../docs/", import.meta.url))) {
    if (name.endsWith(".md") && !excluded.has(name)) files.set(`docs/${name}`, readFileSync(new URL(`../docs/${name}`, import.meta.url), "utf8"));
  }
  files.set("README.md", readFileSync(new URL("../README.md", import.meta.url), "utf8"));
  files.set("prompts/README.md", readFileSync(new URL("../prompts/README.md", import.meta.url), "utf8"));
  return files;
}

function render(): string {
  const upgrades = loadUpgradeRegister();
  const gaps = loadGapRegister();
  const upgradeSummary = summarizeUpgrades(upgrades);
  const gapSummary = summarize(gaps);
  const coverage = scanDesignCoverage(evidenceBase());
  const lines: string[] = [];
  lines.push("## خلاصه ممیزی ماشین‌خوان");
  lines.push("");
  lines.push(`این ممیزی بر پایه ${upgrades.proposals.length} proposal در \`docs/upgrade-register.json\`، ${gaps.gaps.length} gap در \`docs/gap-register.json\` و ${coverage.total} design topic در \`src/core/design-coverage.ts\` تولید شده است.`);
  lines.push("");
  lines.push("| منبع | کل | طراحی/جزئی | غایب یا کامل‌نشده |");
  lines.push("|---|---:|---:|---:|");
  lines.push(`| Upgrade proposals | ${upgrades.proposals.length} | ${upgradeSummary.byImplementationStatus.in_progress} in progress | ${upgradeSummary.byImplementationStatus.not_started} not started |`);
  lines.push(`| Gap register | ${gapSummary.total} | ${gapSummary.byStatus.partial} partial | ${gapSummary.byStatus.missing + gapSummary.byStatus.designed_only} missing/design only |`);
  lines.push(`| Design coverage | ${coverage.total} | ${coverage.designed} designed | ${coverage.thin + coverage.none} thin/none |`);
  lines.push("");
  lines.push("**نتیجه:** در register فعلی هیچ proposalی `done_tested` نیست. بنابراین این ممیزی هیچ قابلیت production را موفق اعلام نمی‌کند. پنج فاز این سری از اولویت‌های P0/P1 انتخاب شده‌اند و هرکدام فقط deterministic kernel و قرارداد قابل‌تست می‌سازند.");
  lines.push("");

  lines.push("## پنج فاز این سری و دامنه انتخاب‌شده");
  lines.push("");
  lines.push("| فاز | عنوان | proposalهای مرتبط | دامنه |");
  lines.push("|---|---|---|---|");
  for (const phase of PHASES) lines.push(`| ${phase.phase} | ${phase.title} | ${phase.proposals} | ${phase.scope} |`);
  lines.push("");
  lines.push("این mapping عمداً overlap دارد: مثلاً API و tenant قبلاً partial هستند اما durable production contract ندارند؛ audit آن‌ها را بسته‌شده فرض نمی‌کند.");
  lines.push("");

  lines.push("## تمام proposalهای ثبت‌شده");
  lines.push("");
  lines.push("| ID | priority | category | status | عنوان |");
  lines.push("|---|---|---|---|---|");
  for (const proposal of upgrades.proposals) {
    const status = proposal.status === "designed_only" ? "📄 designed_only" : proposal.status === "partial" ? "🟡 partial" : proposal.status === "scaffolded" ? "🟠 scaffolded" : "✅ done_tested";
    lines.push(`| \`${proposal.id}\` | ${proposal.priority} | ${proposal.category} | ${status} | ${proposal.titleFa} |`);
  }
  lines.push("");

  lines.push("## proposalهای هنوز شروع‌نشده");
  lines.push("");
  lines.push("این فهرست پاسخ مستقیم به سؤال «چه چیزی تا الان ایجاد نشده؟» است. `designed_only` یعنی طراحی در register وجود دارد، اما کد معتبر/evidence کافی برای capability کامل وجود ندارد.");
  lines.push("");
  lines.push("| ID | priority | عنوان | محل طراحی/بستن |");
  lines.push("|---|---|---|---|");
  for (const proposal of upgrades.proposals.filter((item) => item.implementationStatus === "not_started")) {
    lines.push(`| \`${proposal.id}\` | ${proposal.priority} | ${proposal.titleFa} | ${proposal.implementationLocation.join("، ")} |`);
  }
  lines.push("");

  lines.push("## unresolved gaps بر اساس milestone");
  lines.push("");
  lines.push("| milestone | تعداد gap |");
  lines.push("|---|---:|");
  for (const [milestone, count] of Object.entries(gapSummary.byMilestone)) lines.push(`| ${milestone} | ${count} |`);
  lines.push("");
  lines.push("## قواعد صداقت ممیزی");
  lines.push("");
  lines.push("- contract/kernel، mock، callback یا test unit، production integration نیست.");
  lines.push("- README، Issue، webpage و payload مدل untrusted هستند و authority agent را تغییر نمی‌دهند.");
  lines.push("- raw password ذخیره یا در audit چاپ نمی‌شود؛ CAPTCHA/MFA bypass و bulk account creation ممنوع است.");
  lines.push("- free/local/BYOK مسیر پیش‌فرض باقی می‌ماند و هزینه/egress باید قبل از اجرا deny یا explicit شود.");
  lines.push("- push به `main` و production deploy بدون approval ممنوع است.");
  return lines.join("\n");
}

const before = readFileSync(DOC, "utf8");
const start = before.indexOf(START);
const end = before.indexOf(END);
if (start === -1 || end < start) throw new Error("audit document is missing markers");
const after = `${before.slice(0, start + START.length)}\n\n${render()}\n${before.slice(end)}`;
if (after !== before) writeFileSync(DOC, after, "utf8");
console.log(`capability audit rendered: ${loadUpgradeRegister().proposals.length} proposals, ${loadGapRegister().gaps.length} gaps`);
