import { existsSync, readFileSync, readdirSync } from "node:fs";
import { describe, expect, it } from "vitest";

/**
 * The documentation is a deliverable, so it gets the same treatment as code:
 * internal links must resolve and every referenced source path must exist.
 */

const root = new URL("../", import.meta.url);
const docsDir = new URL("../docs/", import.meta.url);

const docFiles = readdirSync(docsDir).filter((f) => f.endsWith(".md"));
const promptFiles = readdirSync(new URL("../prompts/", import.meta.url)).filter((f) =>
  f.endsWith(".md"),
);

const LINK_RE = /\]\((\.[^)#\s]+)(?:#[^)]*)?\)/g;
const INLINE_CODE_PATH_RE = /`((?:src|schema|examples|prisma|prompts|docs|test)\/[A-Za-z0-9_./-]+)`/g;

function collect(text: string, re: RegExp): string[] {
  const out: string[] = [];
  let m: RegExpExecArray | null;
  re.lastIndex = 0;
  while ((m = re.exec(text)) !== null) {
    if (m[1]) out.push(m[1]);
  }
  return out;
}

describe("documentation integrity", () => {
  it("ships every planned document", () => {
    expect(docFiles.length).toBeGreaterThanOrEqual(16);
    for (const n of [
      "README.md",
      "00-request-review.md",
      "01-product-definition.md",
      "02-roles-and-agents.md",
      "03-architecture.md",
      "04-agent-state-machine.md",
      "05-model-router.md",
      "06-connectors-and-auth.md",
      "07-sandbox-and-security.md",
      "08-memory-and-context.md",
      "09-data-model.md",
      "10-api-and-events.md",
      "11-task-dag-and-scheduling.md",
      "12-quality-and-dod.md",
      "13-roadmap-and-cost.md",
      "14-licensing-and-legal.md",
      "23-upgrade-contracts.md",
      "24-phase-m1-durable-control-plane.md",
      "25-phase-m2-repository-intelligence-and-github-loop.md",
      "26-phase-m3-sandbox-execution-and-security.md",
      "27-phase-m4-product-experience-observability-and-operations.md",
      "28-phase-m5-connector-sdk-and-governed-extensibility.md",
      "29-phase-m6-browser-automation-and-human-in-loop.md",
      "30-phase-m7-deploy-preview-and-release-engineering.md",
      "31-phase-m8-production-reliability-capacity-and-disaster-recovery.md",
      "32-phase-m9-collaboration-and-project-bootstrap.md",
      "33-phase-m10-evaluation-quality-and-consensus.md",
      "34-phase-m11-billing-metering-and-entitlements.md",
      "35-phase-m12-internationalization-and-accessibility.md",
      "36-phase-m13-governed-plugin-ecosystem.md",
      "37-phase-m14-data-governance-and-privacy-lifecycle.md",
      "38-phase-m15-workflow-automation-and-triggers.md",
      "39-phase-m16-memory-and-context-retrieval.md",
      "40-phase-m17-agent-protocol-and-interoperability.md",
      "41-phase-m18-organization-governance-and-policy.md",
      "42-comprehensive-capability-audit.md",
      "43-phase-m19-durable-product-surface-and-event-bus.md",
      "44-phase-m20-evaluation-integrity-and-reproducible-benchmarking.md",
      "45-phase-m21-secure-supply-chain-and-runtime-isolation.md",
      "46-phase-m22-resilience-finops-and-provider-operations.md",
      "47-phase-m23-delivery-trust-and-developer-experience.md",
      "48-phase-m24-intake-planning-and-collaboration.md",
      "49-phase-m25-evidence-grounded-routing-and-operations.md",
      "50-phase-m26-secure-knowledge-fabric.md",
      "51-phase-m27-privacy-aware-retrieval-and-local-index.md",
      "52-phase-m28-governance-quality-and-transparency.md",
      "53-phase-m29-durable-runtime-foundation.md",
      "54-phase-m30-sandbox-execution-and-workspace-runtime.md",
      "55-phase-m31-connector-and-provider-runtime.md",
      "56-phase-m32-operations-evidence-and-disaster-recovery.md",
      "57-phase-m33-product-surface-and-approval-clients.md",
      "58-phase-m34-identity-membership-and-access-runtime.md",
      "59-phase-m35-evaluation-and-benchmark-runtime.md",
      "60-phase-m36-repository-intelligence-and-context-runtime.md",
      "61-phase-m37-preview-artifact-and-delivery-runtime.md",
      "62-phase-m38-security-privacy-and-governance-runtime.md",
      "63-phase-m39-agent-interaction-and-streaming-runtime.md",
      "64-phase-m40-connector-gateway-and-interoperability-runtime.md",
      "65-phase-m41-data-lifecycle-analytics-and-metering-runtime.md",
      "66-phase-m42-quality-ci-and-verification-runtime.md",
      "67-phase-m43-self-host-release-and-resilience-runtime.md",
      "68-phase-m44-collaboration-onboarding-and-run-workspace.md",
      "69-phase-m45-localization-design-and-degraded-clients.md",
      "70-phase-m46-browser-automation-and-external-signals.md",
      "71-phase-m47-legal-licensing-and-enterprise-governance.md",
      "72-phase-m48-production-integration-evidence-and-cutover.md",
      "73-phase-m49-platform-connections-oauth-and-consent.md",
      "74-phase-m50-unified-connector-capabilities-and-actions.md",
      "75-phase-m51-cross-platform-handoff-and-deep-links.md",
      "76-phase-m52-platform-sync-and-conflict-resolution.md",
      "77-phase-m53-connection-center-health-and-fallback.md",
      "78-phase-m54-visual-app-studio-and-prompt-to-ui.md",
      "79-phase-m55-design-to-code-and-ux-verification.md",
      "80-phase-m56-web-ai-model-discovery-and-free-api.md",
      "81-phase-m57-comprehensive-ai-directory-and-model-cards.md",
      "82-phase-m58-model-catalog-governance-and-safe-activation.md",
      "83-phase-m59-visual-studio-integration-and-preview.md",
      "84-phase-m60-model-evaluation-and-trust.md",
      "85-phase-m61-model-provider-runtime-and-routing.md",
      "86-phase-m62-ai-workflow-builder-and-agent-graphs.md",
      "87-phase-m63-ai-platform-operations-and-governance.md",
      "88-phase-m64-product-control-plane-and-api.md",
      "89-phase-m65-durable-persistence-and-event-bus.md",
      "90-phase-m66-sandbox-execution-and-workspace-integration.md",
      "91-phase-m67-external-integration-gates.md",
      "92-phase-m68-pilot-release-and-e2e-gates.md",
      "93-phase-m69-enterprise-identity-and-membership.md",
      "94-phase-m70-privacy-lifecycle-and-data-rights.md",
      "95-phase-m71-developer-experience-and-sdk.md",
      "96-phase-m72-extension-marketplace-and-plugin-trust.md",
      "97-phase-m73-platform-resilience-and-dr.md",
      "98-phase-m74-product-experience-and-accessibility.md",
      "99-phase-m75-evaluation-harness-and-regression.md",
      "100-phase-m76-execution-fabric-and-sandbox.md",
      "101-phase-m77-connector-delivery-and-webhooks.md",
      "102-phase-m78-self-host-release-and-ci.md",
      "103-phase-m79-knowledge-context-and-repository-intelligence.md",
      "104-phase-m80-prompt-safety-and-output-trust.md",
      "105-phase-m81-collaboration-onboarding-and-usage.md",
      "106-phase-m82-integration-adapters-and-browser.md",
      "107-phase-m83-data-governance-legal-and-disclosure.md",
      "108-phase-m84-agent-orchestration-and-checkpoints.md",
      "109-phase-m85-api-worker-and-stream-runtime.md",
      "110-phase-m86-provider-economics-and-routing.md",
      "111-phase-m87-quality-integration-and-e2e.md",
      "112-phase-m88-release-certification-and-cutover.md",
      "113-phase-m89-observability-and-incident-command.md",
      "114-phase-m90-durable-data-plane-and-search.md",
      "115-phase-m91-billing-and-entitlements.md",
      "116-phase-m92-approval-review-and-escalation.md",
      "117-phase-m93-deployment-operations-and-self-host.md",
      "118-phase-m94-retrieval-memory-and-feedback.md",
      "119-phase-m95-supply-chain-and-injection-security.md",
      "120-phase-m96-browser-signal-and-webhook-delivery.md",
      "121-phase-m97-localization-and-degraded-clients.md",
      "122-phase-m98-workspace-bootstrap-and-handoff.md",
      "123-phase-m99-agent-delegation-and-streaming.md",
      "124-phase-m100-workflow-queue-and-scheduling.md",
      "125-phase-m101-connectors-and-platform-gates.md",
      "126-phase-m102-privacy-retention-and-tenant-boundary.md",
      "127-phase-m103-evaluation-and-release-quality.md",
      "128-phase-m104-api-contracts-and-stream-reconnect.md",
      "129-phase-m105-identity-and-membership.md",
      "130-phase-m106-artifact-preview-and-delivery.md",
      "131-phase-m107-observability-and-finops.md",
      "132-phase-m108-self-host-and-controlled-cutover.md",
      "133-phase-m109-context-assembly-and-repository-intelligence.md",
      "134-phase-m110-model-discovery-and-ai-directory.md",
      "135-phase-m111-plugin-marketplace-and-extension-trust.md",
      "136-phase-m112-product-collaboration-and-onboarding.md",
      "137-phase-m113-data-plane-and-analytics.md",
      "138-phase-m114-legal-disclosure-and-output-rights.md",
      "139-phase-m115-provider-routing-and-economics.md",
      "140-phase-m116-platform-sync-and-health.md",
      "141-phase-m117-abuse-safety-and-dlp.md",
      "142-phase-m118-production-evidence-and-cutover.md",
      "143-phase-m119-durable-tenant-and-transaction-runtime.md",
      "144-phase-m120-verification-ci-security-accessibility.md",
      "145-phase-m121-sdk-cli-config-developer-handoff.md",
      "146-phase-m122-key-rotation-erasure-deletion-proof-backup.md",
      "147-phase-m123-capacity-circuit-breaker-resilience.md",
      "148-phase-m124-audit-evidence-ledger-and-replay.md",
      "149-phase-m125-identity-continuity-session-revocation.md",
      "150-phase-m126-connector-consent-webhook-reconciliation.md",
      "151-phase-m127-benchmark-replay-release-quality.md",
      "152-phase-m128-finops-quota-and-provider-allocation.md",
      "153-phase-m129-api-evolution-stream-reconnect.md",
      "154-phase-m130-artifact-supply-chain-and-attestation.md",
      "155-phase-m131-approval-operations-and-escalation.md",
      "156-phase-m132-knowledge-freshness-and-context-lineage.md",
      "157-phase-m133-self-host-upgrade-and-controlled-cutover.md",
      "158-phase-m134-data-portability-and-controlled-import.md",
      "159-phase-m135-device-pairing-and-local-trust.md",
      "160-phase-m136-policy-distribution-and-drift.md",
      "161-phase-m137-incident-case-and-containment.md",
      "162-phase-m138-privacy-preserving-telemetry-and-feedback.md",
      "163-phase-m139-observability-slo-and-trace-integrity.md",
      "164-phase-m140-search-query-governance.md",
      "165-phase-m141-workflow-scheduler-and-triggers.md",
      "166-phase-m142-artifact-lifecycle-and-preview-isolation.md",
      "167-phase-m143-operator-console-and-live-run-ux.md",
      "168-phase-m144-public-api-surface-and-openapi.md",
      "169-phase-m145-connector-sdk-oauth-lifecycle.md",
      "170-phase-m146-workspace-vfs-and-sandbox-boundary.md",
      "171-phase-m147-tenant-isolation-and-rls-proof.md",
      "172-phase-m148-e2e-release-acceptance-and-readiness.md",
      "173-phase-m149-worker-queue-retry-and-dlq.md",
      "174-phase-m150-database-migration-and-schema-governance.md",
      "175-phase-m151-github-app-and-webhook-action.md",
      "176-phase-m152-preview-environment-and-routing.md",
      "177-phase-m153-product-e2e-orchestration-and-containment.md",
      "178-phase-m159-data-residency-and-regional-routing.md",
      "179-phase-m160-feature-flags-and-progressive-rollout.md",
      "180-phase-m161-workload-identity-and-service-account-leases.md",
      "181-phase-m162-data-rights-export-and-deletion.md",
      "182-phase-m163-finops-budget-guardrails-and-reconciliation.md",
      "183-phase-m164-structured-output-repair-and-response-safety.md",
      "184-phase-m165-agent-delegation-and-capability-tokens.md",
      "185-phase-m166-cancellation-and-compensation-runtime.md",
      "186-phase-m167-reproducible-build-and-release-manifest.md",
      "187-phase-m168-outbound-webhook-and-callback-delivery.md",
      "188-phase-m169-context-provenance-and-injection-firewall.md",
      "189-phase-m170-tool-action-boundary-and-transactional-approval.md",
      "190-phase-m171-offline-sync-and-conflict-resolution.md",
      "191-phase-m172-accessibility-and-localization-verification.md",
      "192-phase-m173-incident-learning-and-runbook-automation.md",
      "223-phase-m204-run-handoff-and-human-takeover.md",
      "224-phase-m205-capability-attestation-and-trust-bound-activation.md",
      "225-phase-m206-region-bound-processing-and-residency-enforcement.md",
      "226-phase-m207-action-simulation-and-blast-radius-preview.md",
      "227-phase-m208-policy-change-control-and-rollback.md",
    ]) {
      expect(docFiles, n).toContain(n);
    }
  });

  it("has no broken relative markdown links", () => {
    const broken: string[] = [];
    for (const file of [...docFiles.map((f) => ["docs", f]), ...promptFiles.map((f) => ["prompts", f]), ["root", "README.md"]] as Array<[string, string]>) {
      const [dir, name] = file;
      const base = dir === "root" ? root : new URL(`../${dir}/`, import.meta.url);
      const text = readFileSync(new URL(name, base), "utf8");
      for (const link of collect(text, LINK_RE)) {
        const target = new URL(link, new URL(name, base));
        if (!existsSync(target)) broken.push(`${dir}/${name} -> ${link}`);
      }
    }
    expect(broken).toEqual([]);
  }, 30_000);

  it("only references source paths that exist", () => {
    const broken: string[] = [];
    const files: Array<[URL, string]> = [
      ...docFiles.map((f) => [new URL(f, docsDir), `docs/${f}`] as [URL, string]),
      [new URL("README.md", root), "README.md"],
    ];
    for (const [url, label] of files) {
      const text = readFileSync(url, "utf8");
      for (const p of collect(text, INLINE_CODE_PATH_RE)) {
        const clean = p.replace(/\/$/, "");
        if (!existsSync(new URL(clean, root))) broken.push(`${label} -> ${clean}`);
      }
    }
    expect(broken).toEqual([]);
  });

  it("gives each follow-up phase an explicit threat model", () => {
    for (const file of [
      "53-phase-m29-durable-runtime-foundation.md",
      "54-phase-m30-sandbox-execution-and-workspace-runtime.md",
      "55-phase-m31-connector-and-provider-runtime.md",
      "56-phase-m32-operations-evidence-and-disaster-recovery.md",
      "57-phase-m33-product-surface-and-approval-clients.md",
      "58-phase-m34-identity-membership-and-access-runtime.md",
      "59-phase-m35-evaluation-and-benchmark-runtime.md",
      "60-phase-m36-repository-intelligence-and-context-runtime.md",
      "61-phase-m37-preview-artifact-and-delivery-runtime.md",
      "62-phase-m38-security-privacy-and-governance-runtime.md",
      "63-phase-m39-agent-interaction-and-streaming-runtime.md",
      "64-phase-m40-connector-gateway-and-interoperability-runtime.md",
      "65-phase-m41-data-lifecycle-analytics-and-metering-runtime.md",
      "66-phase-m42-quality-ci-and-verification-runtime.md",
      "67-phase-m43-self-host-release-and-resilience-runtime.md",
      "68-phase-m44-collaboration-onboarding-and-run-workspace.md",
      "69-phase-m45-localization-design-and-degraded-clients.md",
      "70-phase-m46-browser-automation-and-external-signals.md",
      "71-phase-m47-legal-licensing-and-enterprise-governance.md",
      "72-phase-m48-production-integration-evidence-and-cutover.md",
      "73-phase-m49-platform-connections-oauth-and-consent.md",
      "74-phase-m50-unified-connector-capabilities-and-actions.md",
      "75-phase-m51-cross-platform-handoff-and-deep-links.md",
      "76-phase-m52-platform-sync-and-conflict-resolution.md",
      "77-phase-m53-connection-center-health-and-fallback.md",
      "78-phase-m54-visual-app-studio-and-prompt-to-ui.md",
      "79-phase-m55-design-to-code-and-ux-verification.md",
      "80-phase-m56-web-ai-model-discovery-and-free-api.md",
      "81-phase-m57-comprehensive-ai-directory-and-model-cards.md",
      "82-phase-m58-model-catalog-governance-and-safe-activation.md",
      "83-phase-m59-visual-studio-integration-and-preview.md",
      "84-phase-m60-model-evaluation-and-trust.md",
      "85-phase-m61-model-provider-runtime-and-routing.md",
      "86-phase-m62-ai-workflow-builder-and-agent-graphs.md",
      "87-phase-m63-ai-platform-operations-and-governance.md",
      "88-phase-m64-product-control-plane-and-api.md",
      "89-phase-m65-durable-persistence-and-event-bus.md",
      "90-phase-m66-sandbox-execution-and-workspace-integration.md",
      "91-phase-m67-external-integration-gates.md",
      "92-phase-m68-pilot-release-and-e2e-gates.md",
      "93-phase-m69-enterprise-identity-and-membership.md",
      "94-phase-m70-privacy-lifecycle-and-data-rights.md",
      "95-phase-m71-developer-experience-and-sdk.md",
      "96-phase-m72-extension-marketplace-and-plugin-trust.md",
      "97-phase-m73-platform-resilience-and-dr.md",
      "98-phase-m74-product-experience-and-accessibility.md",
      "99-phase-m75-evaluation-harness-and-regression.md",
      "100-phase-m76-execution-fabric-and-sandbox.md",
      "101-phase-m77-connector-delivery-and-webhooks.md",
      "102-phase-m78-self-host-release-and-ci.md",
      "103-phase-m79-knowledge-context-and-repository-intelligence.md",
      "104-phase-m80-prompt-safety-and-output-trust.md",
      "105-phase-m81-collaboration-onboarding-and-usage.md",
      "106-phase-m82-integration-adapters-and-browser.md",
      "107-phase-m83-data-governance-legal-and-disclosure.md",
      "108-phase-m84-agent-orchestration-and-checkpoints.md",
      "109-phase-m85-api-worker-and-stream-runtime.md",
      "110-phase-m86-provider-economics-and-routing.md",
      "111-phase-m87-quality-integration-and-e2e.md",
      "112-phase-m88-release-certification-and-cutover.md",
      "113-phase-m89-observability-and-incident-command.md",
      "114-phase-m90-durable-data-plane-and-search.md",
      "115-phase-m91-billing-and-entitlements.md",
      "116-phase-m92-approval-review-and-escalation.md",
      "117-phase-m93-deployment-operations-and-self-host.md",
      "118-phase-m94-retrieval-memory-and-feedback.md",
      "119-phase-m95-supply-chain-and-injection-security.md",
      "120-phase-m96-browser-signal-and-webhook-delivery.md",
      "121-phase-m97-localization-and-degraded-clients.md",
      "122-phase-m98-workspace-bootstrap-and-handoff.md",
      "123-phase-m99-agent-delegation-and-streaming.md",
      "124-phase-m100-workflow-queue-and-scheduling.md",
      "125-phase-m101-connectors-and-platform-gates.md",
      "126-phase-m102-privacy-retention-and-tenant-boundary.md",
      "127-phase-m103-evaluation-and-release-quality.md",
      "128-phase-m104-api-contracts-and-stream-reconnect.md",
      "129-phase-m105-identity-and-membership.md",
      "130-phase-m106-artifact-preview-and-delivery.md",
      "131-phase-m107-observability-and-finops.md",
      "132-phase-m108-self-host-and-controlled-cutover.md",
      "133-phase-m109-context-assembly-and-repository-intelligence.md",
      "134-phase-m110-model-discovery-and-ai-directory.md",
      "135-phase-m111-plugin-marketplace-and-extension-trust.md",
      "136-phase-m112-product-collaboration-and-onboarding.md",
      "137-phase-m113-data-plane-and-analytics.md",
      "138-phase-m114-legal-disclosure-and-output-rights.md",
      "139-phase-m115-provider-routing-and-economics.md",
      "140-phase-m116-platform-sync-and-health.md",
      "141-phase-m117-abuse-safety-and-dlp.md",
      "142-phase-m118-production-evidence-and-cutover.md",
      "143-phase-m119-durable-tenant-and-transaction-runtime.md",
      "144-phase-m120-verification-ci-security-accessibility.md",
      "145-phase-m121-sdk-cli-config-developer-handoff.md",
      "146-phase-m122-key-rotation-erasure-deletion-proof-backup.md",
      "147-phase-m123-capacity-circuit-breaker-resilience.md",
      "148-phase-m124-audit-evidence-ledger-and-replay.md",
      "149-phase-m125-identity-continuity-session-revocation.md",
      "150-phase-m126-connector-consent-webhook-reconciliation.md",
      "151-phase-m127-benchmark-replay-release-quality.md",
      "152-phase-m128-finops-quota-and-provider-allocation.md",
      "153-phase-m129-api-evolution-stream-reconnect.md",
      "154-phase-m130-artifact-supply-chain-and-attestation.md",
      "155-phase-m131-approval-operations-and-escalation.md",
      "156-phase-m132-knowledge-freshness-and-context-lineage.md",
      "157-phase-m133-self-host-upgrade-and-controlled-cutover.md",
      "158-phase-m134-data-portability-and-controlled-import.md",
      "159-phase-m135-device-pairing-and-local-trust.md",
      "160-phase-m136-policy-distribution-and-drift.md",
      "161-phase-m137-incident-case-and-containment.md",
      "162-phase-m138-privacy-preserving-telemetry-and-feedback.md",
      "163-phase-m139-observability-slo-and-trace-integrity.md",
      "164-phase-m140-search-query-governance.md",
      "165-phase-m141-workflow-scheduler-and-triggers.md",
      "166-phase-m142-artifact-lifecycle-and-preview-isolation.md",
      "167-phase-m143-operator-console-and-live-run-ux.md",
      "168-phase-m144-public-api-surface-and-openapi.md",
      "169-phase-m145-connector-sdk-oauth-lifecycle.md",
      "170-phase-m146-workspace-vfs-and-sandbox-boundary.md",
      "171-phase-m147-tenant-isolation-and-rls-proof.md",
      "172-phase-m148-e2e-release-acceptance-and-readiness.md",
      "173-phase-m149-worker-queue-retry-and-dlq.md",
      "174-phase-m150-database-migration-and-schema-governance.md",
      "175-phase-m151-github-app-and-webhook-action.md",
      "176-phase-m152-preview-environment-and-routing.md",
      "177-phase-m153-product-e2e-orchestration-and-containment.md",
      "178-phase-m159-data-residency-and-regional-routing.md",
      "179-phase-m160-feature-flags-and-progressive-rollout.md",
      "180-phase-m161-workload-identity-and-service-account-leases.md",
      "181-phase-m162-data-rights-export-and-deletion.md",
      "182-phase-m163-finops-budget-guardrails-and-reconciliation.md",
      "183-phase-m164-structured-output-repair-and-response-safety.md",
      "184-phase-m165-agent-delegation-and-capability-tokens.md",
      "185-phase-m166-cancellation-and-compensation-runtime.md",
      "186-phase-m167-reproducible-build-and-release-manifest.md",
      "187-phase-m168-outbound-webhook-and-callback-delivery.md",
      "188-phase-m169-context-provenance-and-injection-firewall.md",
      "189-phase-m170-tool-action-boundary-and-transactional-approval.md",
      "190-phase-m171-offline-sync-and-conflict-resolution.md",
      "191-phase-m172-accessibility-and-localization-verification.md",
      "192-phase-m173-incident-learning-and-runbook-automation.md",
    ]) {
      const text = readFileSync(new URL(file, docsDir), "utf8");
      expect(text).toContain("## Threat Model");
      expect(text).toContain("## معماری");
    }
  });

  it("documents every module of the deterministic core", () => {
    const all = docFiles.map((f) => readFileSync(new URL(f, docsDir), "utf8")).join("\n");
    for (const module of [
      "state-machine.ts",
      "policy-engine.ts",
      "model-router.ts",
      "redaction.ts",
      "task-dag.ts",
      "evidence.ts",
      "output-contract.ts",
      "collaboration.ts",
      "project-scaffold.ts",
      "evaluation.ts",
      "consensus.ts",
      "entitlements.ts",
      "i18n.ts",
      "plugin-registry.ts",
      "data-governance.ts",
      "workflow-automation.ts",
      "memory-retrieval.ts",
      "agent-protocol.ts",
      "org-governance.ts",
      "control-plane-contract.ts",
      "evaluation-integrity.ts",
      "secure-supply-chain.ts",
      "resilience-operations.ts",
      "delivery-trust.ts",
      "intake-and-collaboration.ts",
      "evidence-routing-operations.ts",
      "knowledge-fabric.ts",
      "privacy-retrieval.ts",
      "governance-quality.ts",
      "durable-runtime-contract.ts",
      "execution-sandbox-contract.ts",
      "connector-provider-runtime.ts",
      "operations-evidence.ts",
      "product-surface-contract.ts",
      "identity-access-contract.ts",
      "evaluation-runtime-contract.ts",
      "repository-context-runtime.ts",
      "delivery-preview-runtime.ts",
      "security-privacy-governance-runtime.ts",
      "agent-interaction-runtime.ts",
      "connector-gateway-runtime.ts",
      "data-lifecycle-analytics-runtime.ts",
      "quality-ci-runtime.ts",
      "self-host-resilience-runtime.ts",
      "collaboration-onboarding-runtime.ts",
      "localization-design-runtime.ts",
      "browser-signal-runtime.ts",
      "legal-enterprise-governance-runtime.ts",
      "production-cutover-evidence.ts",
      "platform-connection-runtime.ts",
      "unified-connector-runtime.ts",
      "platform-handoff-runtime.ts",
      "platform-sync-runtime.ts",
      "connection-health-runtime.ts",
      "visual-app-studio-runtime.ts",
      "design-to-code-runtime.ts",
      "model-discovery-runtime.ts",
      "ai-directory-runtime.ts",
      "model-catalog-governance-runtime.ts",
      "visual-studio-integration-runtime.ts",
      "model-evaluation-trust-runtime.ts",
      "model-provider-runtime.ts",
      "ai-workflow-builder-runtime.ts",
      "ai-platform-operations-runtime.ts",
      "product-control-plane-runtime.ts",
      "durable-persistence-runtime.ts",
      "execution-integration-runtime.ts",
      "external-integration-gate-runtime.ts",
      "pilot-release-gate-runtime.ts",
      "enterprise-identity-runtime.ts",
      "privacy-lifecycle-runtime.ts",
      "developer-experience-runtime.ts",
      "extension-marketplace-runtime.ts",
      "platform-resilience-runtime.ts",
      "product-experience-runtime.ts",
      "evaluation-harness-runtime.ts",
      "execution-fabric-runtime.ts",
      "connector-delivery-runtime.ts",
      "self-host-release-runtime.ts",
      "knowledge-context-runtime.ts",
      "prompt-safety-runtime.ts",
      "collaboration-usage-runtime.ts",
      "integration-adapter-runtime.ts",
      "data-governance-runtime.ts",
      "agent-orchestration-runtime.ts",
      "api-worker-runtime.ts",
      "provider-economics-runtime.ts",
      "quality-integration-runtime.ts",
      "release-certification-runtime.ts",
      "observability-incident-runtime.ts",
      "durable-data-plane-runtime.ts",
      "billing-entitlement-runtime.ts",
      "approval-review-runtime.ts",
      "deployment-operations-runtime.ts",
      "retrieval-memory-runtime.ts",
      "supply-chain-security-runtime.ts",
      "browser-signal-delivery-runtime.ts",
      "localization-client-runtime.ts",
      "workspace-bootstrap-runtime.ts",
      "agent-delegation-stream-runtime.ts",
      "workflow-queue-runtime.ts",
      "connector-platform-runtime.ts",
      "privacy-retention-runtime.ts",
      "evaluation-quality-runtime.ts",
      "api-contract-runtime.ts",
      "identity-membership-runtime.ts",
      "artifact-preview-delivery-runtime.ts",
      "observability-finops-runtime.ts",
      "release-cutover-runtime.ts",
      "context-assembly-runtime.ts",
      "model-discovery-directory-runtime.ts",
      "plugin-marketplace-runtime.ts",
      "product-collaboration-runtime.ts",
      "data-plane-analytics-runtime.ts",
      "legal-disclosure-runtime.ts",
      "provider-routing-economics-runtime.ts",
      "platform-sync-health-runtime.ts",
      "abuse-safety-runtime.ts",
      "production-evidence-runtime.ts",
    ]) {
      expect(all, module).toContain(module);
    }
  });
});
